// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "e639bb5c-b176-4c92-bcbd-48f302aff323");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1680789429);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1680789436);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{583b6dee-f175-465e-970e-7b8e098dc8cb}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1680789398);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{fe57111d-9dbf-403f-be83-2a1db153763e}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1680789405);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1680789431069");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1680811031069");
user_pref("browser.search.region", "BR");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230309232621");
user_pref("browser.startup.homepage_override.mstone", "102.9.0");
user_pref("browser.startup.lastColdStartupCheck", 1680789406);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("distribution.iniFile.exists.appversion", "102.9.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "BR");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "11262199d9dc4c58972b52232f4a6eae");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230309232621");
user_pref("extensions.lastAppVersion", "102.9.0");
user_pref("extensions.lastPlatformVersion", "102.9.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"b292aea5-dbd9-4500-b28b-1598487a1da2\",\"formautofill@mozilla.org\":\"0fd4f69e-ee88-46bc-b632-45f6abf65304\",\"pictureinpicture@mozilla.org\":\"1b23ae51-69aa-4c2f-9519-baed618531e1\",\"screenshots@mozilla.org\":\"944b3377-a32e-407b-b54c-b4f111497d75\",\"webcompat-reporter@mozilla.org\":\"239b7ed0-3e53-459b-990f-146bda4f389a\",\"webcompat@mozilla.org\":\"4eb4ed63-e1cc-456a-b7ce-8cffd9407a10\",\"default-theme@mozilla.org\":\"e31c0b71-2864-470e-b6cd-c2b543bb1273\",\"addons-search-detection@mozilla.com\":\"b63d31a8-627f-4a49-b741-57287201c356\",\"google@search.mozilla.org\":\"62fb386b-e6b7-4dd3-9407-62caca9f74c8\",\"amazondotcom@search.mozilla.org\":\"477f5128-53a7-4b37-9a6a-dcb8b9cd2cd1\",\"wikipedia@search.mozilla.org\":\"7854a9fc-4d3b-4f72-9b3e-744494606e63\",\"bing@search.mozilla.org\":\"b159c133-a988-430e-9b27-c325cb21be8c\",\"ddg@search.mozilla.org\":\"8f280f58-4602-488e-bb42-53f5873d34fc\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.eme.enabled", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "db68edc8-861b-4694-82e1-a0c7420d8cd4");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.engine.addresses.available", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.startup.last_success", 1680789392);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20230309232621");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
